---
provider_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"

provider_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: nxapi
  use_ssl: yes
  port: 8443
  validate_certs: no

vlans_common:
  - vlan_id: 301
    name: blue
  - vlan_id: 302
    name: red
  - vlan_id: 303
    name: green

snmp_location: Seattle, WA, USA
snmp_contact: erik_ingeberg@hotmail.com
