---
- name: Configure IP addresses
  hosts: nxos
  tasks:
    - nxos_l3_interface:
        provider: "{{ provider_nxapi }}"
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        ipv6: "{{ item.ipv6 }}"
      with_items: "{{ ip_add }}"
      notify: write mem

  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
      changed_when: True
