---
- name: IOS Config Change
  hosts: pynet-rtr1
  gather_facts: False
  roles:
    - ios_config

- name: EOS Config Change
  hosts: pynet-sw7
  gather_facts: False
  roles:
    - eos_config

- name: NXOS Config Change
  hosts: nxos2
  gather_facts: False
  roles:
    - nxos_config
