---
- name: Save show version output
  hosts: cisco
  vars:
    file_name: "{{ inventory_hostname }}-show_version.txt"
  tasks:
    - name: Get show version
      ios_command:
        provider: "{{ provider_ssh }}"
        commands: show version
      register: output

    - set_fact:
        show_version: "{{ output.stdout[0] }}"

    - copy:
        content: "{{ show_version }}"
        dest: "{{ file_name }}"
