---
- name: Configure static routes
  hosts: pynet-sw5
  vars:
    gw: 10.220.88.1
  tasks:
    - eos_config:
        provider: "{{ provider_eapi }}"
        lines:
          - ip route 1.1.10.1/32 {{ gw }}
          - ip route 1.1.20.1/32 {{ gw }}
          - ip route 1.1.30.1/32 {{ gw }}
          - ip route 1.1.40.1/32 {{ gw }}
